#!/usr/bin/env bash

# ----------------------------------------------------------------------------
# Buildkite script to run kibana flaky runner against ESS
#
# Author: Liza Dayoub
# ----------------------------------------------------------------------------

set -euo pipefail

echo "steps:"
echo "  - block: \"Flaky Test Runner Input\""
echo "    prompt: \"Fill out details\""
echo "    fields:"
echo "      - text: \":large_blue_circle: PR Number\""
echo "        key: github-prnum"
echo "        hint: \"Fill in PR, if you want to test a branch instead use last three fields\""
echo "        required: false"
echo "      - text: \":red_circle: Cloud Version\""
echo "        key: cloud-version"
echo "        hint: \"Cloud version: 7.6.0, 7.6.1-SNAPSHOT...\""
echo "        required: true"
echo "      - text: \":red_circle: Test Configurations\""
echo "        key: test-configs"
echo "        hint: \"Configurations files in the kibana repo comma delimited: x-pack/test/apm_api_integration/trial/config.ts\""
echo "        required: false"
echo "      - text: \":red_circle: Basic CI Group *Use for pre-8.3 versions*\""
echo "        key: basic-ci-group"
echo "        hint: \"CI Group in test/functional/apps directory\""
echo "        required: false"
echo "      - text: \":red_circle: Xpack CI Group *Use for pre-8.3 versions*\""
echo "        key: xpack-ci-group"
echo "        hint: \"CI Group in x-pack/test/functional/apps directory\""
echo "        required: false"
echo "      - select: \":red_circle: Number Of Executions\""
echo "        key: num-executions"
echo "        hint: \"How many times the tests will run\""
echo "        required: true"
echo "        default: 1"
echo "        options:"
echo "          - label: 1"
echo "            value: 1"
echo "          - label: 5"
echo "            value: 5"
echo "          - label: 10"
echo "            value: 10"
echo "          - label: 20"
echo "            value: 20"
echo "          - label: 30"
echo "            value: 30"
echo "          - label: 40"
echo "            value: 40"
echo "          - label: 50"
echo "            value: 50"
echo "      - text: \":white_circle: Github Owner *Skip if using PR Number*\""
echo "        key: github-owner"
echo "        hint: \"If you're testing a fork, this would typically be your username. Otherwise, 'elastic'\""
echo "        required: false"
echo "        default: elastic"
echo "      - text: \":white_circle: Github Repo *Skip if using PR Number*\""
echo "        key: github-repo"
echo "        hint: \"If you're forked repo is called something other than 'kibana'\""
echo "        required: false"
echo "        default: kibana"
echo "      - text: \":white_circle: Github Branch *Skip if using PR Number*\""
echo "        key: github-branch"
echo "        hint: \"The git branch specifier to test with (branch, tag, commit hash...etc)\""
echo "        required: false"
echo "  - wait"
echo "  - label: \":console: Annotation Test\""
echo "    agents:"
echo "      queue: kibana-default"
echo "    command: |"
echo "      buildkite-agent annotate '<b>Information</b><br>' --style 'info' --context 'ctx-info'"
